[package]
name = "cm0889-lab2"
version = "0.1.0"
authors = ["lfrg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"